[package]
name = "cellar-core"
version = "0.1.0"
authors = ["Stephan Göppentin <dedda102@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
jni = "0.18"

[lib]
crate_type = ["cdylib"]